// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAspEShop2024.DataAccessLayer;

#nullable disable

namespace ProjectAspEShop2024.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20231006053428_AddBrand")]
    partial class AddBrand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectAspEShop2024.Domains.Brand", b =>
                {
                    b.Property<long>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ProjectAspEShop2024.Domains.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ProjectAspEShop2024.Domains.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<long>("BrandOfProductBrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryOfProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandOfProductBrandId");

                    b.HasIndex("CategoryOfProductCategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ProjectAspEShop2024.Domains.Product", b =>
                {
                    b.HasOne("ProjectAspEShop2024.Domains.Brand", "BrandOfProduct")
                        .WithMany("ProductsOfBrand")
                        .HasForeignKey("BrandOfProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAspEShop2024.Domains.Category", "CategoryOfProduct")
                        .WithMany("ProductsOfCategory")
                        .HasForeignKey("CategoryOfProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandOfProduct");

                    b.Navigation("CategoryOfProduct");
                });

            modelBuilder.Entity("ProjectAspEShop2024.Domains.Brand", b =>
                {
                    b.Navigation("ProductsOfBrand");
                });

            modelBuilder.Entity("ProjectAspEShop2024.Domains.Category", b =>
                {
                    b.Navigation("ProductsOfCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
